import { Oxanium } from "next/font/google";
import '@/styles/globals.css';

const oxanium = Oxanium({ subsets: ["latin"] });

export const metadata = {
  title: "Underdogg | Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oxanium.className}>{children}</body>
    </html>
  );
}
